//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4_WS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public package()
        {
            this.route_item = new HashSet<route_item>();
        }
    
        public long id { get; set; }
        public string description { get; set; }
        public string destinationCity { get; set; }
        public string name { get; set; }
        public string senderCity { get; set; }
        public Nullable<bool> tracking { get; set; }
        public Nullable<long> receiver_id { get; set; }
        public Nullable<long> sender_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<route_item> route_item { get; set; }
    }
}
